### PR TITLE
docs: Add CSV file with the GDS layer informations and comments

### PR DESCRIPTION
**Pull request by smunaut**
This is from https://docs.google.com/spreadsheets/d/176OcP2h_TT_pDP2-zBLijlgFUP38LVgMQPlDtpLcrsk/edit?ts=5eff8387#gid=459375686

Signed-off-by: Sylvain Munaut <tnt@246tNt.com>

### CODE REVIEW

**Comment by mithro** [comment]
I would also be awesome to have a small Python script which updates the `.csv` file by using the Google sheet's export to CSV functionality. Something like;
```
    data = urllib.request.urlopen(
        "https://docs.google.com/spreadsheets/d/e/2PACX-1vTmqEM-XXPW4oHrJMD7QrCeKOiq1CPng9skQravspmEmaCt04Kz4lTlQLFTyQyJhcjqzCc--eO2f11x/pub?output=csv"
    ).read().decode('utf-8')
```

**Comment by mithro** [comment]
BTW - I think I fixed the publish permission on the Google spreadsheet you linked.

**Comment by smunaut** [comment]
(1) Huh, why do I need that ?  I don't really want it in the sidebar, it's a subitem of the "process stackup" which is already not in that sidebar or in that TOC because it's "too deep" in the hierarchy.  I just put it into a separate file rather than inline because it's a large table.

(2) Do we really want an external google docs as the "reference" ?  I thought this was just a convenient place to put it up initially but that the "main" reference would eventually be this repository. (a bit like open-pdk will eventually me merged/moved here).

**Comment by mithro** [comment]
I'll merge it as currently and follow up on the other two topics.

**Pull request merged**
