### PR TITLE
Removed duplicated keys from previous.rst

### LINKED ISSUE #160: Fix sphinx warnings in docs/previous.rst
When building the documentation, the `docs/previous.rst` gives the following warnings.
```
/home/tim/github/google/skywater-pdk/docs/previous.rst:38: WARNING: glossary terms must not be separated by empty lines  
/home/tim/github/google/skywater-pdk/docs/previous.rst:42: WARNING: duplicate term description of s8phirs, other instance in previous
/home/tim/github/google/skywater-pdk/docs/previous.rst:45: WARNING: duplicate term description of s8phrc, other instance in previous
```
These should be fixed.

### PR DESCRIPTION
**Pull request by wgryncewicz**
Fixes #160

### CODE REVIEW

**Comment by mithro** [comment]
@wgryncewicz - I'm unsure if this is the right fix? Where do the other definitions come from?

**Comment by wgryncewicz** [comment]
Not sure as there's no file history beyond initial commit. 
Possibly it was generated?
https://github.com/google/skywater-pdk/edit/master/docs/previous.rst
Lines #L32 and #L37 contain just keys, without definition.
Respective definitions are under duplicated entries #L46 and #L43.

**Review by mithro — CHANGES_REQUESTED** [review]
Can we instead add descriptions?

**Comment by wgryncewicz** [comment]
> Can we instead add descriptions?

I'm not sure if I understand correctly... `s8phirs` nad `s8phrc` keys with descriptions are already there, slightly below:
```
    :lib_process:`s8phirs`
        The base process plus rdl layer and rdl metal inductors.

    :lib_process:`s8phrc`
        The base process plus dual MiM cap layers on metal 3 and metal 4
```

Should I keep the duplicated keys and add duplicated description?

**Review by mithro — APPROVED** [review]
Welp, I'm just blind it seems.

**Pull request merged**
