### PR TITLE
Change to new theme

### PR DESCRIPTION
**Pull request by daniellimws**
Signed-off-by: Daniel Lim Wee Soong <weesoong.lim@gmail.com>

Update docs/requirements.txt to use the new SymbiFlow theme, and update conf.py to remove extra options and use the correct name for the primary and accent colors.

Also update primary color to green to improve readability. (Any comments on this?)

- [x] Tests pass
- [x] Appropriate changes to README are included in PR

### CODE REVIEW

**Review by umarcor — APPROVED** [review]

**Comment by mithro** [comment]
We have lost a bit of functionality with this change.
 - The green colors have changed.
 - The links in the headers.
 - The expandable left hand headers.

**Comment by daniellimws** [comment]
I was trying out the darker green color as I think it is more readable, changed it back to the light green that was used before.

Also, I realized I missed out the Github and skywater links as you mentioned, and have added them already.

Currently the theme does not support expanding the headers on the left bar. I can work on adding them.

**Comment by daniellimws** [comment]
Modified the theme to allow expanding of the toc links. https://github.com/SymbiFlow/sphinx_symbiflow_theme/pull/8

**Comment by mithro** [comment]
This pull request was replaced by https://github.com/google/skywater-pdk/pull/341

There are still some follow on work which needs to be investigated;
 - https://github.com/SymbiFlow/sphinx_symbiflow_theme/issues/10
 - https://github.com/SymbiFlow/sphinx_symbiflow_theme/issues/11

**Pull request closed without merging**
