### PR TITLE
Convert submodule sources to be github versions.

### PR DESCRIPTION
**Pull request by mithro**
Signed-off-by: Tim 'mithro' Ansell <me@mith.ro>

### CODE REVIEW

**Comment by mithro** [comment]
FYI - @agorararmard

**Comment by mithro** [comment]
FYI - @RTimothyEdwards

**Comment by RTimothyEdwards** [comment]
Thank you, sir!

**Comment by RTimothyEdwards** [comment]
@mithro :  Does this require any change to the way that skywater-pdk is built?

**Comment by mithro** [comment]
@RTimothyEdwards It should be transparent to users. They might want to do a `git submodule sync` after updating if they want to start using the versions from GitHub. The submodule mirrors at https://foss-eda-tools.googlesource.com remain operational (and mirror the github versions).

**Pull request merged**
